#!/bin/sh

. "$(dirname "$0")/.common.sh"

set -e

: ${app_ver:=$(installed_version)}
: ${app_name:=$(grep ^RemotingName $app_ini | cut -f2 -d=)}
: ${api_url:=https://addons.mozilla.org/api/v4/addons/addon}

for ext in "$DESTDIR"/home/user/.mozilla/firefox/*/extensions/*;do
  ext_name="$(basename "$ext" .xpi)"
  ext_info_json="$(dl_file "$api_url/${ext_name}/?app=${app_name}&platform=linux&appversion=${app_ver}")"
  ext_xpi_url="$(jq -r ".current_version.files[0].url" "$ext_info_json")"
  test -n "$ext_xpi_url" -a ! "x$ext_xpi_url" = "xnull" || {
    echo "WARNING: No installable version of extension '$ext_name' for $app_name $app_ver" >&2
    rm -rf "$ext"
    continue
  }
  ext_xpi="$(dl_file "$ext_xpi_url")"
  ext_guid="$(jq -r .guid "$ext_info_json")"
  test "x$ext_guid" = "x$ext_name" || {
    ext_new="${ext%/*}/${ext_guid}$(test -d "$ext" || echo ".xpi")"
    mv "$ext" "$ext_new"
    ext="$ext_new"
  }
  if test -d "$ext";then
    7z x -o"$ext" "$ext_xpi"
  else
    cp -v "$ext_xpi" "$ext"
  fi
done
