#!/bin/sh

. "$(dirname "$0")/.common.sh"

set -e

: ${app_ver:=$(installed_version)}
: ${app_name:=$(grep ^RemotingName $app_ini | cut -f2 -d=)}
: ${api_url:=https://services.addons.mozilla.org/${locale}/${app_name}/api/1.5}

for ext in "$DESTDIR"/home/user/.mozilla/firefox/*/extensions/*;do
  ext_name="$(basename "$ext" .xpi)"
  ext_info_url="$api_url/search/guid:${ext_name}?src=firefox&appOS=Linux&appVersion=${app_ver}"
  ext_url="$(curl -g -s "$ext_info_url" | xmllint --xpath "/searchresults/addon/install/text()" -)"
  ext_xpi="$(dl_file "$ext_url")"
  if test -d "$ext";then
    7z x -o"$ext" "$ext_xpi"
  else
    cp -v "$ext_xpi" "$ext"
  fi
done
